name: SVN to Git Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "manilmunjal@gmail.com"
          git config --global user.name "manilmunjal"

      - name: Install dependencies and resolve package conflicts
        run: |
          sudo apt-get update
          sudo apt-get install -y git-svn=1:2.45.1-0ppa1~ubuntu22.04.1 default-jdk unzip wget
          sudo apt-get -f install
          sudo dpkg --configure -a
          sudo apt-get clean

      - name: Clone SVN repository
        run: |
          svn co --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} https://eu-subversion.assembla.com/svn/anythingispossible^SVN.svn-demo/ svn_repo
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      - name: Set up JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          mv jfrog /usr/local/bin/jfrog
          jfrog config add my-jfrog-server --artifactory-url https://manilmunjalsneo.jfrog.io/artifactory--user ${{ secrets.JFROG_USER }} --password ${{ secrets.JFROG_PASSWORD }} --interactive=false

      - name: Create Git repository
        run: |
          mkdir git_repo
          cd git_repo
          git init

      - name: Copy SVN contents to Git repository
        run: |
          cp -r ../svn_repo/* .

      - name: Upload binaries to JFrog and replace with URL pointers
        run: |
          find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \) | while read binary; do
            binary_name=$(basename "$binary")
            jfrog rt u "$binary" "${{ secrets.JFROG_REPO }}/$binary_name"
