name: SVN to GitHub Migration

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git credentials
        run: |
          git config --global user.email "manilmunjal@gmail.com"
          git config --global user.name "manilmunjal"

      - name: Clone SVN repository and extract JFrog Artifactory URLs
        run: |
          svn co https://eu-subversion.assembla.com/svn/anythingispossible^SVN.svn-demo/ svn_repo --username manilmunjal --password Mu@230841
          cd svn_repo

          # Extract JFrog Artifactory URLs for binary files
          find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \) | while read binary; do
            binary_name=$(basename "$binary")
            jfrog_url="https://manilmunjalsneo.jfrog.io/artifactory/$binary_name"
            echo "$jfrog_url" > "$binary.url"
            git add "$binary.url"
          done

          # Add all files excluding binaries
          find . -type f \( ! -iname "*.exe" -a ! -iname "*.dll" -a ! -iname "*.bin" \) -exec git add {} +

          # Commit URL pointers back to Git instead of binaries
          git commit -m "Test 21212"

      - name: Add GitHub repository as remote
        run: |
          git remote add github_repo https://github.com/manilmunjal/svn-git.git

      - name: Push to GitHub
        run: |
          # git config --global credential.helper store
          # git config --global user.email "$GIT_EMAIL"
          # git config --global user.name "$GIT_NAME"
          # echo "https://SarthakChaudhary46:${{ secrets.PAT }}@github.com/SarthakChaudhary46/Svn2Git" > ~/.git-credentials
          git push --all github_repo
          git push --tags github_repo
          git commit -m "hemlo"
