# name: Binary Migration Workflow

# on:
#   push:
#     branches:
#       - main
# env:
#   SVN_USERNAME: "manilmunjal"
#   SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }} # Make sure to add this secret in repository settings
#   SVN_REPO_URL: "https://eu-subversion.assembla.com/svn/anythingispossible%5ESVN.svn-demo/"
#   JFROG_URL: "https://manilmunjalsneo.jfrog.io/artifactory"
#   JFROG_REPO: "binary-store-generic-local"
#   JFROG_USER: "manil.m@statusneo.com"
#   JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }} # Make sure to add this secret in repository settings
#   GIT_REPO_URL: "https://${{ secrets.PAT }}@github.com/manilmunjal/svn-git.git"
# jobs:
#   migrate:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Install Git and SVN
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y git subversion

#       # - name: Set up environment
#       #   run: |
#       #     export PATH="$PATH:/usr/bin/git:/usr/bin/svn"

#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Define variables
     

#       # Extract binaries and upload to JFrog
#       - name: Extract binaries and upload to JFrog
#         run: |
#           git config --global user.name "manilmunjal"
#           git config --global user.email "manilmunjal@gmail.com"

#           # Extract binaries
#           mkdir -p binaries
#           svn co --username "$SVN_USERNAME" --password "$SVN_PASSWORD" "$SVN_REPO_URL" binaries

#           # Install JFrog CLI
#           curl -fL https://getcli.jfrog.io | sh
#           mv jfrog /usr/local/bin/jfrog

#           # Configure JFrog CLI
#           jfrog config add my-jfrog-server --artifactory-url $JFROG_URL --user $JFROG_USER --password $JFROG_PASSWORD --interactive=false
          
#           # Upload binaries to JFrog and commit URLs to Git
#           cd binaries
#           for binary in $(find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \)); do
#             binary_name=$(basename "$binary")
#             jfrog rt u "$binary" "$JFROG_REPO/$binary_name"
#             jfrog_url="$JFROG_URL/$JFROG_REPO/$binary_name"
#             echo "$jfrog_url" > "$binary.url"
#           done
#           git init
#           git add .
#           git commit -m "Add JFrog URL pointers"
#           git push -u origin master

#       # # Clone SVN repository and perform SVN to Git migration
#       # - name: SVN to Git migration
#       #   run: |
#       #     # Clone SVN repository
#       #     svn co --username $SVN_USERNAME --password $SVN_PASSWORD $SVN_REPO_URL svn_repo

#       #     # Run svn2git migration
#       #     git svn clone $SVN_REPO_URL --authors-file=authors.txt --no-metadata -s git_repo
#       #     cd git_repo
#       #     git remote add origin $GIT_REPO_URL
#       #     git push -u origin master

name: Binary Migration Workflow

on:
  push:
    branches:
      - main
      # Define variables
env:
  # PAT: ${{ secrets.PAT }}
  SVN_REPO_URL: "https://eu-subversion.assembla.com/svn/anythingispossible%5ESVN.svn-demo/"
  SVN_USERNAME: "manilmunjal"
  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }} # Make sure to add this secret in repository settings
  JFROG_URL: "https://manilmunjalsneo.jfrog.io/artifactory"
  JFROG_REPO: "binary-store-generic-local"
  JFROG_USER: "manil.m@statusneo.com"
  JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }} # Make sure to add this secret in repository settings
  GIT_REPO_URL: "https://${{secrets.PAT}}@github.com/manilmunjal/svn-git.git"
  GIT_TOKEN: ${{secrets.PAT}}



jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install required packages
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y git-svn
      #     sudo apt-get install -y default-jdk
      #     sudo apt-get install -y unzip

      # Define variables
      # Extract binaries and upload to JFrog
      - name: Extract binaries and upload to JFrog
        run: |
          # Install JFrog CLI
          curl -fL https://getcli.jfrog.io | sh
          mv jfrog /usr/local/bin/jfrog

           # Configure JFrog CLI
          jfrog config add my-jfrog-server --artifactory-url $JFROG_URL --user $JFROG_USER --password $JFROG_PASSWORD --interactive=false
          git config --global user.name "manilmunjal"
          git config --global user.email "manilmunjal@gmail.com"
          # Extract binaries
          # mkdir binaries
          # Your commands to extract binaries, e.g., unzip or copy
          mkdir -p binaries
          svn co --username "$SVN_USERNAME" --password "$SVN_PASSWORD" "$SVN_REPO_URL" binaries
          
          # Upload binaries to JFrog and commit URLs to Git
          cd binaries
          find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \) | while read binary; do
            binary_name=$(basename "$binary")
            jfrog rt u "$binary" "$JFROG_REPO/$binary_name"
            jfrog_url="$JFROG_URL/$JFROG_REPO/$binary_name"
            echo "$jfrog_url" > "$binary.url"
            git add "$binary.url"
          done
          git commit -m "Add JFrog URL pointers"
          git push
      # # SVN to Git migration using svn2git
      # - name: SVN to Git migration
      #   run: |
      #     # Clone SVN repository

      - name: Clone SVN repository using svn2git
        run: |


           sudo apt-get update
           sudo apt-get install -y subversion git
           sudo apt-get install -y git-svn
           svn checkout <SVN_URL> svn_repo
           cd svn_repo
           svn2git
           cd svn_repo
           git remote add origin <GIT_REPO_URL>
           git push -u origin master

          
          # # sudo apt-get update
          # # sudo apt-get install -y subversion
          # # sudo apt-get install -y ruby ruby-dev
          # # sudo apt-get install -y git=1:2.33.0-1ubuntu1 git-svn subversion
          # sudo apt-get remove git

          # # Add repository with the desired version (if necessary)
          # # For example, if you want to use version 2.33.0-1ubuntu1:
          # # sudo add-apt-repository ppa:git-core/ppa
          
          # # Install the older version of git
          # sudo apt-get install git=2.33.0-1ubuntu1
          
          # # Hold the package to prevent automatic upgrades
          # sudo apt-mark hold git
          
          # # Verify the installation
          # git --version
          # # sudo apt-get update
          # sudo apt-get install -y subversion
          # sudo apt-get install -y ruby ruby-dev
          # sudo apt-get install -y git git-svn
          # sudo gem install svn2git
          #!/bin/bash

          # #!/bin/bash

          # # Remove the existing git package
          # sudo apt-get remove git
          
          # # Download the specific version of git .deb package
          # wget http://security.ubuntu.com/ubuntu/pool/main/g/git/git_2.33.0-1ubuntu1_amd64.deb
          
          # # Install the downloaded git package
          # sudo dpkg -i git_2.33.0-1ubuntu1_amd64.deb
          
          # # Hold the package to prevent automatic upgrades
          # sudo apt-mark hold git
          
          # # Verify the installation
          # git --version
          
          # # Install additional required packages
          # sudo apt-get update
          # sudo apt-get install -y subversion
          # sudo apt-get install -y ruby ruby-dev
          # sudo apt-get install -y git-svn
          # sudo gem install svn2git

          # svn2git $SVN_REPO_URL --username $SVN_USERNAME --password $SVN_PASSWORD --no-minimize-url
          # git remote add origin $GIT_REPO_URL
          # git push -u origin --all
          # git push --tags



       
